services:
  - type: web
    name: html-copyright-analyzer
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        generateValue: true
    healthCheckPath: /health
    autoDeploy: true
    disk:
      name: html-analyzer-disk
      mountPath: /opt/render/project/src
      sizeGB: 1